version: '3.9'

services:
  libreria-app:
    build: .
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/libreria_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_ENABLED: "true"
      EXTERNAL_API_BOOKS_URL: https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books
    volumes:
      - h2_data:/data

volumes:
  h2_data:
